// ============================================================
// Enums — mirror backend app/schemas/investigation_state.py
// ============================================================

/** Processing status of an individual agent. */
export enum AgentStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

/** Category of a detected anomaly. */
export enum AnomalyType {
  POINT = "POINT",
  BEHAVIORAL = "BEHAVIORAL",
  CONTEXTUAL = "CONTEXTUAL",
  NETWORK = "NETWORK",
  MERCHANT = "MERCHANT",
  SEASONAL = "SEASONAL",
}

/** Severity rating for anomalies and compliance findings. */
export enum SeverityLevel {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

/** Possible resolution actions for a case. */
export enum DecisionAction {
  ALLOW = "ALLOW",
  HOLD = "HOLD",
  BLOCK = "BLOCK",
  ESCALATE = "ESCALATE",
}

/** Pipeline stage the investigation is currently in. */
export enum CurrentStage {
  INTAKE = "INTAKE",
  CONTEXT = "CONTEXT",
  REASONING = "REASONING",
  COMPLIANCE = "COMPLIANCE",
  DECISION = "DECISION",
  REPORTING = "REPORTING",
  DONE = "DONE",
}

/** Lifecycle status of a supporting document's processing. */
export enum ProcessingStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  EXTRACTED = "EXTRACTED",
  SUMMARIZED = "SUMMARIZED",
  FAILED = "FAILED",
}

// ============================================================
// Reusable Domain Models
// ============================================================

/** A single financial transaction under investigation. */
export interface Transaction {
  transaction_id: string;
  amount: number;
  currency: string;
  timestamp: string;
  sender_account: string;
  receiver_account: string;
  transaction_type: string;
  channel: string;
  description?: string;
  location?: string;
}

/** Profile of the customer associated with the case. */
export interface CustomerProfile {
  customer_id: string;
  name: string;
  email?: string;
  phone?: string;
  address?: string;
  date_of_birth?: string;
  account_open_date?: string;
  risk_rating?: string;
  occupation?: string;
  nationality?: string;
}

/** Details about the merchant involved in the transaction. */
export interface MerchantInfo {
  merchant_id: string;
  name: string;
  category: string;
  country?: string;
  risk_level?: SeverityLevel;
  registered_date?: string;
}

/** Device and session metadata captured during the transaction. */
export interface DeviceInfo {
  device_id?: string;
  device_type?: string;
  ip_address?: string;
  geolocation?: string;
  is_known_device: boolean;
  os?: string;
  browser?: string;
}

/** Information about the payment beneficiary. */
export interface BeneficiaryInfo {
  beneficiary_id: string;
  name: string;
  account_number: string;
  bank_name?: string;
  country?: string;
  is_new: boolean;
  relationship?: string;
}

/** Behavioral biometric signals captured during the session. */
export interface BehavioralBiometrics {
  typing_speed?: number;
  mouse_dynamics?: string;
  session_duration_seconds?: number;
  anomaly_score?: number;
}

/** Outcome of facial verification during the session. */
export interface FaceVerificationResult {
  is_verified: boolean;
  confidence_score?: number;
  method?: string;
  timestamp?: string;
}

/** A document attached as evidence to the case. */
export interface SupportingDocument {
  document_id: string;
  document_type: string;
  file_name?: string;
  file_url?: string;
  uploaded_at?: string;
  summary?: string;
  extracted_text?: string;
  extracted_entities: string[];
  extracted_transactions: string[];
  evidence_references: string[];
  processing_status: ProcessingStatus;
}

/** A single compliance regulation mapped to the case. */
export interface ComplianceMapping {
  regulation_id: string;
  regulation_name: string;
  description?: string;
  is_violated: boolean;
  severity: SeverityLevel;
  evidence_references: string[];
}

/** An investigation hypothesis generated by the reasoning agent. */
export interface Hypothesis {
  hypothesis_id: string;
  title: string;
  description: string;
  confidence: number;
  supporting_evidence: string[];
  contradicting_evidence: string[];
}

/** An anomaly detected during analysis. */
export interface DetectedAnomaly {
  anomaly_id: string;
  anomaly_type: AnomalyType;
  severity: SeverityLevel;
  description: string;
  related_transactions: string[];
}

/** A possible resolution option with rationale. */
export interface DecisionOption {
  option_id: string;
  action: DecisionAction;
  rationale: string;
  confidence: number;
  risk_score?: number;
  pros: string[];
  cons: string[];
  risks: string[];
  mitigation: string[];
}

/** A node in the investigation relationship graph. */
export interface GraphNode {
  node_id: string;
  label: string;
  node_type: string;
  metadata: Record<string, string>;
}

/** An edge connecting two nodes in the investigation graph. */
export interface GraphEdge {
  source: string;
  target: string;
  relationship: string;
  /** Serialised as null (not omitted) for unweighted edges by the backend. */
  weight?: number | null;
}

/** Full graph structure for visualization. */
export interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

/** An error recorded during agent execution. */
export interface AgentError {
  agent_name: string;
  error_type: string;
  message: string;
  timestamp: string;
}

/** A single event in the investigation timeline. */
export interface TimelineEvent {
  timestamp: string;
  event_name: string;
  stage?: CurrentStage;
}

// ============================================================
// Higher-Level Agent Output Models
// ============================================================

/** Raw inputs that initiate an investigation case. */
export interface CaseInput {
  transactions: Transaction[];
  customer_profile?: CustomerProfile;
  merchant_info?: MerchantInfo;
  device_info?: DeviceInfo;
  beneficiary_info?: BeneficiaryInfo;
  behavioral_biometrics?: BehavioralBiometrics;
  face_verification?: FaceVerificationResult;
  supporting_documents: SupportingDocument[];
  alert_reason?: string;
}

/** Output of the Context & Evidence Intelligence agent. */
export interface ContextIntelligence {
  status: AgentStatus;
  context_summary?: string;
  key_indicators: string[];
  anomalies: DetectedAnomaly[];
  risk_score?: number;
}

/** Output of the Investigation Reasoning agent. */
export interface InvestigationReasoning {
  status: AgentStatus;
  hypotheses: Hypothesis[];
  reasoning_summary?: string;
  recommended_actions: string[];
}

/** Output of the Evidence & Compliance Validation agent. */
export interface EvidenceComplianceValidation {
  status: AgentStatus;
  compliance_mappings: ComplianceMapping[];
  evidence_gaps: string[];
  validation_summary?: string;
}

/** Output of the Decision Optimization agent. */
export interface DecisionOptimization {
  status: AgentStatus;
  decision_options: DecisionOption[];
  recommended_decision?: DecisionAction;
  decision_rationale?: string;
}

/** Graph visualizations included in the investigation report. */
export interface ReportGraphs {
  entity_relationship_graph?: GraphData;
  reasoning_graph?: GraphData;
  decision_comparison_graph?: GraphData;
  investigation_timeline: TimelineEvent[];
}

/** Output of the Reporting & Visualization agent. */
export interface InvestigationReport {
  status: AgentStatus;
  executive_summary?: string;
  detailed_narrative?: string;
  graphs?: ReportGraphs;
  generated_at?: string;
}

// ============================================================
// Root Investigation State
// ============================================================

/**
 * Single shared state object for the entire investigation pipeline.
 * Every LangGraph node reads from and writes to this state.
 */
export interface InvestigationState {
  case_id: string;
  case_input: CaseInput;
  context_intelligence?: ContextIntelligence;
  investigation_reasoning?: InvestigationReasoning;
  evidence_compliance_validation?: EvidenceComplianceValidation;
  decision_optimization?: DecisionOptimization;
  investigation_report?: InvestigationReport;
  current_stage: CurrentStage;
  created_at: string;
  updated_at: string;
  errors: AgentError[];
}

// ============================================================
// Convenience Types for UI
// ============================================================

/** Lightweight summary for the investigation list page. */
export interface InvestigationListItem {
  case_id: string;
  customer_name: string;
  current_stage: CurrentStage;
  risk_score?: number;
  created_at: string;
  alert_reason?: string;
}


/**
 * An investigation officer, as rendered in collaboration UI.
 *
 * `initial` is computed by the backend from the authenticated account's name,
 * so the avatar never depends on a hardcoded letter.
 */
export interface Investigator {
  user_id: string;
  full_name: string;
  email?: string | null;
  initial: string;
  /** The identifier the officer signs in with, e.g. "OFF-001". */
  officer_id?: string | null;
  role?: string | null;
}
