import { fireEvent, render, screen } from "@testing-library/react";
import { InvestigationGraphs } from "@/components/investigations/InvestigationGraphs";
import type { ReportGraphs } from "@/types";

/**
 * The reasoning graph is generated by the backend on every completed case, but
 * it lives in a <details> section. Collapsing it by default made it look like
 * it had stopped being produced, so these tests pin that it is visible when the
 * data exists — and that a reviewer's own collapse is not undone by the
 * investigation page's polling re-renders.
 */

const graphs: ReportGraphs = {
  entity_relationship_graph: {
    nodes: [
      { node_id: "CUST-001", label: "Test Customer", node_type: "PERSON", metadata: {} },
      { node_id: "ACC-SRC", label: "ACC-SRC", node_type: "ACCOUNT", metadata: {} },
      { node_id: "ACC-DST", label: "ACC-DST", node_type: "ACCOUNT", metadata: {} },
    ],
    edges: [
      { source: "CUST-001", target: "ACC-SRC", relationship: "OWNS", weight: null },
      { source: "ACC-SRC", target: "ACC-DST", relationship: "SENT_TO", weight: 48000 },
    ],
  },
  reasoning_graph: {
    nodes: [
      { node_id: "TXN-001", label: "TXN-001", node_type: "EVIDENCE", metadata: {} },
      { node_id: "HYP-001", label: "Unauthorised use", node_type: "HYPOTHESIS", metadata: {} },
      { node_id: "BSA-1020.320", label: "SAR", node_type: "COMPLIANCE", metadata: {} },
      { node_id: "ESCALATE", label: "ESCALATE", node_type: "DECISION", metadata: {} },
    ],
    edges: [
      { source: "TXN-001", target: "HYP-001", relationship: "INFORMS", weight: null },
      { source: "HYP-001", target: "ESCALATE", relationship: "INFORMS", weight: null },
    ],
  },
  decision_comparison_graph: {
    nodes: [{ node_id: "OPT-ESCALATE", label: "ESCALATE", node_type: "OPTION", metadata: {} }],
    edges: [],
  },
  investigation_timeline: [],
};

describe("InvestigationGraphs", () => {
  it("renders the entity graph from backend-supplied nodes", () => {
    render(<InvestigationGraphs graphs={graphs} />);

    expect(screen.getByText("Entity Relationship Graph")).toBeInTheDocument();
    // Labels render both in the SVG and the accompanying node list.
    expect(screen.getAllByText("Test Customer").length).toBeGreaterThan(0);
    expect(screen.getAllByText("ACC-SRC").length).toBeGreaterThan(0);
  });

  it("shows the reasoning graph expanded when the backend supplies it", () => {
    render(<InvestigationGraphs graphs={graphs} />);

    const details = screen.getByText(/Reasoning & decision graphs/i).closest("details");
    expect(details).toHaveAttribute("open");
    expect(screen.getByText("Reasoning Graph")).toBeInTheDocument();
    expect(screen.getByText("Unauthorised use")).toBeInTheDocument();
  });

  it("keeps a reviewer's collapse across a re-render", () => {
    const { rerender } = render(<InvestigationGraphs graphs={graphs} />);
    const details = screen.getByText(/Reasoning & decision graphs/i).closest("details")!;

    // jsdom does not fire toggle on its own; emulate the browser.
    details.open = false;
    fireEvent(details, new Event("toggle", { bubbles: false }));
    rerender(<InvestigationGraphs graphs={graphs} />);

    expect(screen.getByText(/Reasoning & decision graphs/i).closest("details")).not.toHaveAttribute("open");
  });

  it("omits the secondary section entirely when there is no reasoning data", () => {
    const withoutSecondary: ReportGraphs = {
      ...graphs,
      reasoning_graph: { nodes: [], edges: [] },
      decision_comparison_graph: { nodes: [], edges: [] },
    };

    render(<InvestigationGraphs graphs={withoutSecondary} />);

    expect(screen.queryByText(/Reasoning & decision graphs/i)).not.toBeInTheDocument();
  });

  it("renders an empty state rather than crashing when graphs are absent", () => {
    render(<InvestigationGraphs graphs={null} />);

    expect(screen.getByText("Entity Relationship Graph")).toBeInTheDocument();
    expect(
      screen.getByText("No relationship data available for this investigation."),
    ).toBeInTheDocument();
  });
});
